-- MySQL Script generated by MySQL Workbench
-- Sat Oct  3 16:37:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `criacao` DATETIME NULL,
  `alteracao` DATETIME NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL,
  `conteudo` MEDIUMTEXT NOT NULL,
  `autores` VARCHAR(100) NULL,
  `id_usuario` INT NOT NULL,
  `criacao` DATETIME NULL,
  `alteracao` DATETIME NULL,
  `status` INT NULL,
  `descricao` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_post_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categorias` (
  `titulo` VARCHAR(255) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `criacao` DATETIME NULL,
  `alteracao` DATETIME NULL,
  `descricao` MEDIUMTEXT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `post_categoria` (
  `id_post` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_post`, `id_categoria`),
  CONSTRAINT `fk_post_has_categorias_post1`
    FOREIGN KEY (`id_post`)
    REFERENCES `posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_categorias_categorias1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO projetoblogJava.users (nome, email, password, id, criacao, alteracao, status) VALUES ('Vinicius Secari', 'vinicius@secari.com', '$2a$10$01OQkiV3fZl3uKgP8FyLRe6lke3SWXj5AQ1elJurchCe0fiJxb4ga', 1, '2020-10-17 13:03:45', '2020-10-17 13:03:51', 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
